name: clang-format

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: install tools
      run: |
        sudo add-apt-repository 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main'
        sudo apt install clang-format-9
    - name: clang-format
      run: |
        ./minirake clang_format
